name: gis-2025
services:
- name: server
  github:
    branch: main
    deploy_on_push: true
    repo: elipe/gis-2025-back
  dockerfile_path: server/Dockerfile
  source_dir: server
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: MONGODB_URI
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: NODE_ENV
    scope: RUN_TIME
    value: production

- name: client
  github:
    branch: main
    deploy_on_push: true
    repo: elipe/gis-2025-back
  dockerfile_path: client/Dockerfile
  source_dir: client
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: / 