name: gis-2025
services:
- name: server
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/gis-2025-back
  dockerfile_path: server/Dockerfile
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: ${MONGODB_URI}
  - key: JWT_SECRET
    value: ${JWT_SECRET}

- name: client
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/gis-2025-back
  dockerfile_path: client/Dockerfile
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: VITE_API_URL
    value: https://${DOMAIN}/api 