name: gis-2025
services:
- name: server
  github:
    branch: main
    deploy_on_push: true
    repo: elipe/gis-2025-back
  source_dir: server
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: npm install
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: MONGODB_URI
    value: ${MONGODB_URI}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: PORT
    value: "5000"

- name: client
  github:
    branch: main
    deploy_on_push: true
    repo: elipe/gis-2025-back
  source_dir: client
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  build_command: npm install && npm run build
  run_command: npm run preview -- --host 0.0.0.0 --port 80
  envs:
  - key: VITE_API_URL
    value: https://${DOMAIN}/api 