name: gis-2025
services:
- name: server
  github:
    branch: eli_pentser_final
    deploy_on_push: true
    repo: pentser/gis-2025-back
  dockerfile_path: server/Dockerfile
  source_dir: server
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: MONGODB_URI
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: NODE_ENV
    scope: RUN_TIME
    value: production
  health_check:
    http_path: /api/health
    initial_delay_seconds: 30
    period_seconds: 10

- name: client
  github:
    branch: eli_pentser_final
    deploy_on_push: true
    repo: pentser/gis-2025-back
  dockerfile_path: client/Dockerfile
  source_dir: client
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 10 